### ISSUE TITLE
Create MS XMP metadata

### ISSUE THREAD

**Issue by ivanooi** [dragon66/icafe#78] opened 2018-07-23 11:01 UTC
Hi,

  Not sure why. I can't create the MS XMP. Custom XMP no problem. 

This is the sample XMP generated by MS ( Right mouse click, properties -> Detail, Copyright field )
Thanks

```
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.1.0-jc003">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
      xmpMM:InstanceID="uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b">
      <dc:rights>
        <rdf:Alt>
          <rdf:li xml:lang="x-default">My Copyright</rdf:li>
        </rdf:Alt>
      </dc:rights>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
    
<?xpacket end="w"?>

```

This is the code :  
`
         
         ls_ns = "http://purl.org/dc/elements/1.1/";
         ( XMPMetaFactory.getSchemaRegistry()).registerNamespace( ls_ns, "dc" );

         if( meta.doesArrayItemExist( ls_ns, "rights", 1 )){
            meta.setArrayItem( ls_ns, "rights", 1, "My Copyright");
         }else{
            meta.deleteProperty( ls_ns, "rights");
            meta.setProperty ( ls_ns, "rights"   , "My Copyright");
         }

         ls_xmp = XMPMetaFactory.serializeToString( meta, new SerializeOptions().setPadding(10));
         System.out.println("ls_xmp=\r\n" + ls_xmp);
         metaList.add( new JpegXMP( ls_xmp ));

         FileInputStream  fin = new FileInputStream(  "A.JPG");
         FileOutputStream fout= new FileOutputStream( "B.JPG");
         
         Metadata.insertMetadata(metaList, fin, fout );

`

**Comment by dragon66** [comment] 2018-07-24 00:09
Are you saying the code didn’t add the XMP to the image? How did you know it’s not there? Did you try to read the image meta data using icafe after?

**Comment by ivanooi** [comment] 2018-07-24 00:11
yes, I did. the XMP XML not there. and I had tired right click -> Properties -> Detail. You can't the info in Copyright filed

**Comment by dragon66** [comment] 2018-07-24 00:16
When you do the console output, did you get the string you created?

**Comment by ivanooi** [comment] 2018-07-24 00:32
No... that the problem :-(

**Comment by ivanooi** [comment] 2018-07-24 00:35
but there's no problem inserting custom XMP XML.

**Comment by dragon66** [comment] 2018-07-24 01:13
I am confused! What is MS XMP in your case and what do mean by Custom XMP?

**Comment by ivanooi** [comment] 2018-07-24 01:23
This is what generated by MS Windows when you keyin info thru Properties -> Detail 
I would like to generate XMP like what MS Windows generated. 

`<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.1.0-jc003">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
      xmpMM:InstanceID="uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b">
      <dc:rights>
        <rdf:Alt>
          <rdf:li xml:lang="x-default">My Copyright</rdf:li>
        </rdf:Alt>
      </dc:rights>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
    
<?xpacket end="w"?>`

Custom mean, I create my own. 
eg : 

`<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.1.0-jc003">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:TEST="ns:www.test.my/"
      TEST:area_code="ML40"
      TEST:user_area_code="ML40"/>
  </rdf:RDF>
</x:xmpmeta>
    
<?xpacket end="w"?>` 

Thanks

**Comment by dragon66** [comment] 2018-07-24 02:11
Now I see. So you create custom XMP manually and used Adobe API to try to create something similar to what MS did but could’t create the XMP properly?

**Comment by ivanooi** [comment] 2018-07-24 02:48
yes yes yes! :-D

**Comment by ivanooi** [comment] 2018-07-24 02:49
Actually I'm using icafe. This is the code :  

`     ls_ns = "http://purl.org/dc/elements/1.1/";
     ( XMPMetaFactory.getSchemaRegistry()).registerNamespace( ls_ns, "dc" );

     if( meta.doesArrayItemExist( ls_ns, "rights", 1 )){
        meta.setArrayItem( ls_ns, "rights", 1, "My Copyright");
     }else{
        meta.deleteProperty( ls_ns, "rights");
        meta.setProperty ( ls_ns, "rights"   , "My Copyright");
     }

     ls_xmp = XMPMetaFactory.serializeToString( meta, new SerializeOptions().setPadding(10));
     System.out.println("ls_xmp=\r\n" + ls_xmp);
     metaList.add( new JpegXMP( ls_xmp ));

     FileInputStream  fin = new FileInputStream(  "A.JPG");
     FileOutputStream fout= new FileOutputStream( "B.JPG");
     
     Metadata.insertMetadata(metaList, fin, fout );`

**Comment by ivanooi** [comment] 2018-07-24 22:09
I see ...hmm....so , there is no way to add that using icafe, right?

**Comment by dragon66** [comment] 2018-07-25 00:36
I guess you already added that but you won't see it when you right click as it tries to show the element value, not the attribute.

**Comment by ivanooi** [comment] 2018-07-25 00:42
anyway to store the data in element not?

**Comment by ivanooi** [comment] 2018-07-25 00:55
If added at the correct place, I believe you will be able to see the data in Detail section... that the purpose :-P

**Comment by dragon66** [comment] 2018-07-25 00:56
As an element or perhaps array element as shown in your initial question when you add it through MS.

You can can actually try insert directly the XMP file you extracted from MS in your original question using icafe, you should see it afterwards. That way, you will prove it is the issue I mentioned which prevent it from showing.

**Comment by ivanooi** [comment] 2018-07-25 00:59
direct modify the xml file. that's another way. I will try that. good idea

**Comment by dragon66** [comment] 2018-07-25 15:20
I am closing this thread as the issue is not directly related to icafe. I tried insert the XMP string provided in your initial question and it works fine. As I mentioned earlier, icafe doesn't provide function to actually create XMP in the first place. It just insert ready-made XMP in string or byte array format into different kinds of images.

**Closed by dragon66** 2018-07-25 15:20 UTC
Labels: invalid

**Comment by ivanooi** [comment] 2018-07-29 18:23
Thanks. Finally I managed to use Adobe XMP to construct Microsoft XMP. Thanks again :-D
